/*
 * subsystemIdRanges.h
 *
 *  Created on: Jul 27, 2018
 *      Author: gaisser
 */

#ifndef FSFWCONFIG_TMTC_SUBSYSTEMIDRANGES_H_
#define FSFWCONFIG_TMTC_SUBSYSTEMIDRANGES_H_

namespace SUBSYSTEM_ID {
enum {
DUMMY = 10,
CENTROID_WRITER,
POINTING_WRITER,
SENSOR_WRITER,
};
}


#endif /* FSFWCONFIG_TMTC_SUBSYSTEMIDRANGES_H_ */
