#ifndef FSFWCONFIG_TMTC_PUSIDS_H_
#define FSFWCONFIG_TMTC_PUSIDS_H_

namespace pus {
enum {
	PUS_SERVICE_1 = 1,
	PUS_SERVICE_2 = 2,
	PUS_SERVICE_3 = 3,
	PUS_SERVICE_5 = 5,
	PUS_SERVICE_8 = 8,
	PUS_SERVICE_9 = 9,
	PUS_SERVICE_17 = 17,
	PUS_SERVICE_200 = 200,
	PUS_PARAMETER_SERVICE=20
};

}



#endif /* FSFWCONFIG_TMTC_PUSIDS_H_ */
